from pydantic import BaseModel, Field

class BrainIteration(BaseModel):
    self_thought: str = Field(
        ...,
        description="Guide the LLM with instructions on how to approach the query for the current iteration based on history.",
    )
    iteration_stop: bool = Field(
        ...,
        description="False for continue, True to stop the iteration as LLM has given the final confident answer for the query",
    )

class LLMResponse(BaseModel):
    response: str = Field(
        ...,
        description="The response generated by the LLM to the brain's prompt",
    )
    answer_to_query: bool = Field(
        ...,
        description="Does the response contain the final answer to the query? True if it does, False if it does not",
    )

class GraphOutput(BaseModel):
    llm_response_answer: str = Field("The response Generated by the LLM in respone to the brains prompt that addresses the initial user query")